use_frameworks!

target 'AnimatedTextInput_Example' do
    pod 'AnimatedTextInput', :path => '../'
end

target 'AnimatedTextInput_Tests' do
    pod 'AnimatedTextInput', :path => '../'
    pod 'KIF', '~> 3.5'
    pod 'Nimble', '~> 5.1'
end
