platform :ios, '8.3'

use_frameworks!
inhibit_all_warnings!

target 'AnimatedTextInput_Example' do
    pod 'AnimatedTextInput', :path => '../'
end

target 'AnimatedTextInput_Tests' do
    pod 'AnimatedTextInput', :path => '../'
    pod 'KIF', '~> 3.5'
    pod 'Nimble', '~> 5.1'
    pod 'FBSnapshotTestCase'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
